package cmd

import (
	"fmt"
	"github.com/fengya90/winter-aop/wacli/clean"

	"github.com/spf13/cobra"
)

var (
	cleanCmd = &cobra.Command{
		Use:   "clean",
		Short: "clean the code which is generated by cmd gen",
		Long: `
		clean the code which is generated by cmd gen.
For example:

	wacli clean -d /myhome/mydir1 -d /myhome/mydir2
	wacli clean -f /myhome/myconfig`,
		Run: func(cmd *cobra.Command, args []string) {
			if len(sourceDirs) == 0 && configFilePath == "" {
				fmt.Println("source_dir or  config_file_path is required")
				return
			}
			clean.CleanFunc(sourceDirs, configFilePath)
		},
	}
)

func init() {
	cleanCmd.Flags().StringArrayVarP(&sourceDirs, "source_dir", "d", []string{}, "the source code directories")
	cleanCmd.Flags().StringVarP(&configFilePath, "config_file_path", "f", "", "configuration file for the source code directories")
	rootCmd.AddCommand(cleanCmd)
}
